export const mockDemands = [
  {
    id: "1",
    type: "human",
    description: "需要志工協助清理受災區域的淤泥和垃圾",
    location: { lat: 23.5, lng: 121.0, address: "花蓮縣某區某街" },
    contact: { name: "張先生", phone: "0912-345-678" },
    humanNeed: { required: 20, riskNotes: "請穿著防滑鞋，注意地面濕滑" },
    appliedCount: 5,
    status: "approved",
  },
  {
    id: "2",
    type: "supply",
    description: "災區急需各種民生物資",
    location: { lat: 23.6, lng: 121.1, address: "花蓮縣某鄉某村" },
    contact: { name: "李小姐", phone: "0923-456-789" },
    supplyItems: [
      { itemName: "飲用水", quantity: 100, unit: "箱" },
      { itemName: "泡麵", quantity: 200, unit: "箱" },
      { itemName: "罐頭食品", quantity: 50, unit: "箱" },
      { itemName: "衛生紙", quantity: 30, unit: "箱" },
    ],
    status: "approved",
  },
  {
    id: "3",
    type: "supply",
    description: "學校急需清潔用品",
    location: { lat: 23.55, lng: 121.05, address: "花蓮縣某國小" },
    contact: { name: "王校長", phone: "0934-567-890" },
    supplyItems: [
      { itemName: "漂白水", quantity: 20, unit: "瓶" },
      { itemName: "掃把", quantity: 50, unit: "支" },
      { itemName: "拖把", quantity: 50, unit: "支" },
      { itemName: "垃圾袋", quantity: 100, unit: "包" },
    ],
    status: "approved",
  },
  {
    id: "4",
    type: "human",
    description: "協助災民搬運家當和重建工作",
    location: { lat: 23.7, lng: 121.2, address: "花蓮縣某里某路" },
    contact: { name: "陳太太", phone: "0956-789-012" },
    humanNeed: { required: 15, riskNotes: "需有搬運經驗，注意安全第一" },
    appliedCount: 8,
    status: "approved",
  },
  {
    id: "5",
    type: "site-holding",
    description: "臨時集會點，用於發放物資和登記需求",
    location: { lat: 23.65, lng: 121.15, address: "花蓮縣災害應變中心" },
    contact: { name: "災害應變中心", phone: "03-123-4567" },
    status: "approved",
  },
  {
    id: "6",
    type: "site-parking",
    description: "志工車輛臨時停車場",
    location: { lat: 23.45, lng: 120.95, address: "花蓮縣某停車場" },
    contact: { name: "停車場管理員", phone: "0945-678-901" },
    status: "approved",
  },
  {
    id: "7",
    type: "site-stay",
    description: "災民臨時安置所，提供食宿",
    location: { lat: 23.75, lng: 121.25, address: "花蓮縣某國中" },
    contact: { name: "安置中心主任", phone: "03-234-5678" },
    status: "approved",
  },
  {
    id: "8",
    type: "site-food",
    description: "免費熱食發放點",
    location: { lat: 23.8, lng: 121.3, address: "花蓮縣某活動中心" },
    contact: { name: "志工隊長", phone: "0967-890-123" },
    status: "approved",
  },
  {
    id: "9",
    type: "supply",
    description: "醫療用品緊急需求",
    location: { lat: 23.52, lng: 121.08, address: "花蓮縣某衛生所" },
    contact: { name: "衛生所主任", phone: "03-345-6789" },
    supplyItems: [
      { itemName: "口罩", quantity: 500, unit: "個" },
      { itemName: "消毒酒精", quantity: 100, unit: "瓶" },
      { itemName: "繃帶", quantity: 200, unit: "捲" },
      { itemName: "藥膏", quantity: 50, unit: "罐" },
    ],
    status: "pending",
  },
  {
    id: "10",
    type: "human",
    description: "需要心理輔導志工協助災民情緒支持",
    location: { lat: 23.48, lng: 120.98, address: "花蓮縣某社區中心" },
    contact: { name: "心理輔導員", phone: "0978-901-234" },
    humanNeed: { required: 8, riskNotes: "需有心理輔導相關經驗或訓練" },
    appliedCount: 3,
    status: "approved",
  },
  {
    id: "11",
    type: "supply",
    description: "嬰幼兒用品急需",
    location: { lat: 23.62, lng: 121.12, address: "花蓮縣某托兒所" },
    contact: { name: "托兒所主任", phone: "0989-012-345" },
    supplyItems: [
      { itemName: "嬰兒奶粉", quantity: 30, unit: "罐" },
      { itemName: "尿布", quantity: 200, unit: "包" },
      { itemName: "濕巾", quantity: 100, unit: "包" },
      { itemName: "嬰兒衣服", quantity: 50, unit: "套" },
    ],
    status: "approved",
  },
  {
    id: "12",
    type: "site-parking",
    description: "大型車輛停車區",
    location: { lat: 23.42, lng: 120.92, address: "花蓮縣某工業區" },
    contact: { name: "工業區管理處", phone: "03-456-7890" },
    status: "approved",
  },
];
